using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

public enum ObjectSelectStatus {
    Invalid_OSS,
    ObjectOnscreen_OSS,
    ObjectOffscreen_OSS,
    ObjectNotFound_OSS
}

public enum ObjectInfoEnum {
    DEFAULT_OI = 0,
    CONTACT_OI = (1 << 0),
    ON_WALKABLE_OI = (1 << 1),
    IS_VIEWER_OI = (1 << 2),
    PATH_CLIPPED_OI = (1 << 3),
    FREE_ROTATE_OI = (1 << 4),
    // NOTE: Skip 1
    PERFECT_CLIP_OI = (1 << 6),
    IS_IMPENETRABLE = (1 << 7),
    IS_PLAYER = (1 << 8),
    EDGE_SLIDE = (1 << 9),
    IGNORE_CREATURES = (1 << 10),
    IS_PK = (1 << 11),
    IS_PKLITE = (1 << 12)
}

public enum PKStatusEnum {
    Undef_PKStatus = 0,
    Protected_PKStatus = (1 << 0),
    NPK_PKStatus = (1 << 1),
    PK_PKStatus = (1 << 2),
    Unprotected_PKStatus = (1 << 3),
    RubberGlue_PKStatus = (1 << 4),
    Free_PKStatus = (1 << 5),
    PKLite_PKStatus = (1 << 6),
    Creature_PKStatus = Unprotected_PKStatus, // 8
    Trap_PKStatus = Unprotected_PKStatus, // 8
    NPC_PKStatus = Protected_PKStatus, // 1
    Vendor_PKStatus = RubberGlue_PKStatus, // 16
    Baelzharon_PKStatus = Free_PKStatus // 32
}

public enum AppraisalLongDescDecorations {
    LDDecoration_PrependWorkmanship = (1 << 0),
    LDDecoration_PrependMaterial = (1 << 1),
    LDDecoration_AppendGemInfo = (1 << 2)
}

public enum CreatureType {
    Invalid_CreatureType,
    Olthoi_CreatureType,
    Banderling_CreatureType,
    Drudge_CreatureType,
    Mosswart_CreatureType,
    Lugian_CreatureType,
    Tumerok_CreatureType,
    Mite_CreatureType,
    Tusker_CreatureType,
    Phyntos_Wasp_CreatureType,
    Rat_CreatureType,
    Auroch_CreatureType,
    Cow_CreatureType,
    Golem_CreatureType,
    Undead_CreatureType,
    Gromnie_CreatureType,
    Reedshark_CreatureType,
    Armoredillo_CreatureType,
    Fae_CreatureType,
    Virindi_CreatureType,
    Wisp_CreatureType,
    Knathtead_CreatureType,
    Shadow_CreatureType,
    Mattekar_CreatureType,
    Mumiyah_CreatureType,
    Rabbit_CreatureType,
    Sclavus_CreatureType,
    Shallows_Shark_CreatureType,
    Monouga_CreatureType,
    Zefir_CreatureType,
    Skeleton_CreatureType,
    Human_CreatureType,
    Shreth_CreatureType,
    Chittick_CreatureType,
    Moarsman_CreatureType,
    Olthoi_Larvae_CreatureType,
    Slithis_CreatureType,
    Deru_CreatureType,
    Fire_Elemental_CreatureType,
    Snowman_CreatureType,
    Unknown_CreatureType,
    Bunny_CreatureType,
    Lightning_Elemental_CreatureType,
    Rockslide_CreatureType,
    Grievver_CreatureType,
    Niffis_CreatureType,
    Ursuin_CreatureType,
    Crystal_CreatureType,
    Hollow_Minion_CreatureType,
    Scarecrow_CreatureType,
    Idol_CreatureType,
    Empyrean_CreatureType,
    Hopeslayer_CreatureType,
    Doll_CreatureType,
    Marionette_CreatureType,
    Carenzi_CreatureType,
    Siraluun_CreatureType,
    Aun_Tumerok_CreatureType,
    Hea_Tumerok_CreatureType,
    Simulacrum_CreatureType,
    Acid_Elemental_CreatureType,
    Frost_Elemental_CreatureType,
    Elemental_CreatureType,
    Statue_CreatureType,
    Wall_CreatureType,
    Altered_Human_CreatureType,
    Device_CreatureType,
    Harbinger_CreatureType,
    Dark_Sarcophagus_CreatureType,
    Chicken_CreatureType,
    Gotrok_Lugian_CreatureType,
    Margul_CreatureType,
    Bleached_Rabbit_CreatureType,
    Nasty_Rabbit_CreatureType,
    Grimacing_Rabbit_CreatureType,
    Burun_CreatureType,
    Target_CreatureType,
    Ghost_CreatureType,
    Fiun_CreatureType,
    Eater_CreatureType,
    Penguin_CreatureType,
    Ruschk_CreatureType,
    Thrungus_CreatureType,
    Viamontian_Knight_CreatureType,
    Remoran_CreatureType,
    Swarm_CreatureType,
    Moar_CreatureType,
    Enchanted_Arms_CreatureType,
    Sleech_CreatureType,
    Mukkir_CreatureType,
    Merwart_CreatureType,
    Food_CreatureType,
    Paradox_Olthoi_CreatureType,
    Harvest_CreatureType,
    Energy_CreatureType,
    Apparition_CreatureType,
    Aerbax_CreatureType,
    Touched_CreatureType,
    Blighted_Moarsman_CreatureType,
    Gear_Knight_CreatureType,
    Gurog_CreatureType,
    A_nekshay_CreatureType
}

public enum WeenieType {
    Undef_WeenieType,
    Generic_WeenieType,
    Clothing_WeenieType,
    MissileLauncher_WeenieType,
    Missile_WeenieType,
    Ammunition_WeenieType,
    MeleeWeapon_WeenieType,
    Portal_WeenieType,
    Book_WeenieType,
    Coin_WeenieType,
    Creature_WeenieType,
    Admin_WeenieType,
    Vendor_WeenieType,
    HotSpot_WeenieType,
    Corpse_WeenieType,
    Cow_WeenieType,
    AI_WeenieType,
    Machine_WeenieType,
    Food_WeenieType,
    Door_WeenieType,
    Chest_WeenieType,
    Container_WeenieType,
    Key_WeenieType,
    Lockpick_WeenieType,
    PressurePlate_WeenieType,
    LifeStone_WeenieType,
    Switch_WeenieType,
    PKModifier_WeenieType,
    Healer_WeenieType,
    LightSource_WeenieType,
    Allegiance_WeenieType,
    UNKNOWN__GUESSEDNAME32, // NOTE: Missing 1
    SpellComponent_WeenieType,
    ProjectileSpell_WeenieType,
    Scroll_WeenieType,
    Caster_WeenieType,
    Channel_WeenieType,
    ManaStone_WeenieType,
    Gem_WeenieType,
    AdvocateFane_WeenieType,
    AdvocateItem_WeenieType,
    Sentinel_WeenieType,
    GSpellEconomy_WeenieType,
    LSpellEconomy_WeenieType,
    CraftTool_WeenieType,
    LScoreKeeper_WeenieType,
    GScoreKeeper_WeenieType,
    GScoreGatherer_WeenieType,
    ScoreBook_WeenieType,
    EventCoordinator_WeenieType,
    Entity_WeenieType,
    Stackable_WeenieType,
    HUD_WeenieType,
    House_WeenieType,
    Deed_WeenieType,
    SlumLord_WeenieType,
    Hook_WeenieType,
    Storage_WeenieType,
    BootSpot_WeenieType,
    HousePortal_WeenieType,
    Game_WeenieType,
    GamePiece_WeenieType,
    SkillAlterationDevice_WeenieType,
    AttributeTransferDevice_WeenieType,
    Hooker_WeenieType,
    AllegianceBindstone_WeenieType,
    InGameStatKeeper_WeenieType,
    AugmentationDevice_WeenieType,
    SocialManager_WeenieType,
    Pet_WeenieType,
    PetDevice_WeenieType,
    CombatPet_WeenieType
}
