using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

public enum MaterialType {
    Undef_MaterialType,
    Ceramic_MaterialType,
    Porcelain_MaterialType,
    Cloth_MaterialType,
    Linen_MaterialType,
    Satin_MaterialType,
    Silk_MaterialType,
    Velvet_MaterialType,
    Wool_MaterialType,
    Gem_MaterialType,
    Agate_MaterialType,
    Amber_MaterialType,
    Amethyst_MaterialType,
    Aquamarine_MaterialType,
    Azurite_MaterialType,
    Black_Garnet_MaterialType,
    Black_Opal_MaterialType,
    Bloodstone_MaterialType,
    Carnelian_MaterialType,
    Citrine_MaterialType,
    Diamond_MaterialType,
    Emerald_MaterialType,
    Fire_Opal_MaterialType,
    Green_Garnet_MaterialType,
    Green_Jade_MaterialType,
    Hematite_MaterialType,
    Imperial_Topaz_MaterialType,
    Jet_MaterialType,
    Lapis_Lazuli_MaterialType,
    Lavender_Jade_MaterialType,
    Malachite_MaterialType,
    Moonstone_MaterialType,
    Onyx_MaterialType,
    Opal_MaterialType,
    Peridot_MaterialType,
    Red_Garnet_MaterialType,
    Red_Jade_MaterialType,
    Rose_Quartz_MaterialType,
    Ruby_MaterialType,
    Sapphire_MaterialType,
    Smoky_Quartz_MaterialType,
    Sunstone_MaterialType,
    Tiger_Eye_MaterialType,
    Tourmaline_MaterialType,
    Turquoise_MaterialType,
    White_Jade_MaterialType,
    White_Quartz_MaterialType,
    White_Sapphire_MaterialType,
    Yellow_Garnet_MaterialType,
    Yellow_Topaz_MaterialType,
    Zircon_MaterialType,
    Ivory_MaterialType,
    Leather_MaterialType,
    Armoredillo_Hide_MaterialType,
    Gromnie_Hide_MaterialType,
    Reed_Shark_Hide_MaterialType,
    Metal_MaterialType,
    Brass_MaterialType,
    Bronze_MaterialType,
    Copper_MaterialType,
    Gold_MaterialType,
    Iron_MaterialType,
    Pyreal_MaterialType,
    Silver_MaterialType,
    Steel_MaterialType,
    Stone_MaterialType,
    Alabaster_MaterialType,
    Granite_MaterialType,
    Marble_MaterialType,
    Obsidian_MaterialType,
    Sandstone_MaterialType,
    Serpentine_MaterialType,
    Wood_MaterialType,
    Ebony_MaterialType,
    Mahogany_MaterialType,
    Oak_MaterialType,
    Pine_MaterialType,
    Teak_MaterialType,
    Number_MaterialType = Teak_MaterialType,
    NumMaterialTypes_MaterialType = 238
}
